spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/readme-maker
    username: root
    password: 153035

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true

app:
  jwtSecret: iSPdDmp40rLu/lDDi/01LD0LQekbdtI0Ndaw0F5UhtorV86CsUyBR7plxlF/30jhSiu2HD9sSWh5dd3MMJHCuA==
  jwtExpirationInMs: 86400000